### ISSUE TITLE
`tsup --config tsup.config.js` throws error

### ISSUE THREAD

**Issue by dj184dja8** [egoist/tsup#829]
Hi, 

I use the script `tsup --config tsup.config.js` to bundle my library and it works well in tsup@6.5.0.
However, after upgrading to tsup@6.6.0, the same script throws errors as below.

```
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at createRequire (node:internal/modules/cjs/loader:1224:11)
    at dynamicImport (xxxxx/node_modules/bundle-require/dist/index.cjs:75:154)
    at extractResult (xxxxx/node_modules/bundle-require/dist/index.cjs:190:21)
    at async run (xxxxx/node_modules/bundle-require/dist/index.cjs:228:17)
```

node version: v16.15.1

any idea? thanks a lot!

**Comment by egoist** [comment]
it’s a bug in bundle-require, will fix soon

**Comment by egoist** [comment]
should be fixed now, since it's a fix in tsup's dependency, you can run `npm update` or `pnpm update` to update it

**Comment by praneetloke** [comment]
I still get this error with the latest version `6.7.0`. Going back to `6.5.0` works, though, so I've temporarily pinned to that older version. Let me know if I can help by providing more useful info to debug this.

```
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at createRequire (node:internal/modules/cjs/loader:1220:11)
    at Object.<anonymous> (/Users/praneetloke/GitHub/deskypus/deeplink/node_modules/load-tsconfig/dist/index.cjs:139:107)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/praneetloke/GitHub/deskypus/deeplink/node_modules/bundle-require/dist/index.cjs:43:28)
```

My `tsup` config looks like this:

```typescript
import { defineConfig } from "tsup";
import { isDev } from "./scripts/utils";

export default defineConfig(() => ({
    entry: {
        "background/index": "./src/background/index.ts",
    },
    outDir: "extension/dist",
    format: ["esm"],
    target: "esnext",
    ignoreWatch: ["**/extension/**"],
    splitting: false,
    sourcemap: isDev ? "inline" : false,
    define: {
        __DEV__: JSON.stringify(isDev),
        "process.env.NODE_ENV": JSON.stringify(isDev ? "development" : "production"),
    },
    platform: "browser",
    minifyWhitespace: !isDev,
    minifySyntax: !isDev,
}));
```
